### PR TITLE
Add an object to the realtime repl queue

### PR DESCRIPTION
**Pull request by russelldb**
This PR adds an API to riak_kv that enables a client to tell riak to read an object, and put in on the realtime repl queue, as though the post-commit hook for a write of that object had fired.

The realtime repl queue can drop objects. It may be possible also to detect inter-cluster divergence by external mechanisms (for example writing last-modified as an index and comparing query results between clusters.)  An in progress feature allows rapid cluster contents divergence checking with tic-tac-tree based AAE. Any of these use cases needs a way to prompt replication of an object. This feature provides that.

The API accepts a bucket/key pair, and the many of the same options as a GET. Riak then fetches the object, and enqueues it on the repl queue. Returning `ok` or an error.

### CODE REVIEW

**Comment by martinsumner** [comment]
There are a couple of dialyzer failures:

```
==> riak_kv (dialyzer)
  riak_repl_util:get_hooks_for_modes/0
  riak_object:object/0
make: *** [dialyzer-run] Error 1
```

-spec rt_enqueue_object(riak_object:object()) ->
should be riak_object:riak_object()

In the same function you have

Hooks = riak_repl_util:get_hooks_for_modes(),

I suspect that riak_repl is not pulled in by riak_kv, only by riak

**Comment by russelldb** [comment]
Aargh! Not sure what to do about the repl one. Thanks tho for the heads up. I actually forgot to run dialyzer

**Comment by martinsumner** [comment]
I'm having a look at the moment ... swimming training going on.  

When I added riak_repl to rebar.config ... it pulled in riak_kv as a dependancy, and everything broke!

**Comment by russelldb** [comment]
I'll move the function out to riak_repl instead. It was a mistake to add it to riak_kv

**Pull request merged**
